name: CI/CD Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout python-greetings repository
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'

      - uses: ./.github/actions/build
  
  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout python-greetings repository
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'

      - uses: ./.github/actions/deploy
        with:
          environment: 'dev'
          port: '7001'

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout course-js-api-framework repository
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'

      - uses: ./.github/actions/test
        with:
          environment: 'dev'
    
  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout python-greetings repository
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'

      - uses: ./.github/actions/deploy
        with:
          environment: 'staging'
          port: '7002'

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout course-js-api-framework repository
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'

      - uses: ./.github/actions/test
        with:
          environment: 'staging'

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout python-greetings repository
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'

      - uses: ./.github/actions/deploy
        with:
          environment: 'preprod'
          port: '7003'

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout course-js-api-framework repository
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'

      - uses: ./.github/actions/test
        with:
          environment: 'preprod'

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout python-greetings repository
        with:
          repository: 'mtararujs/python-greetings'
          path: 'python-greetings'

      - uses: ./.github/actions/deploy
        with:
          environment: 'prod'
          port: '7004'

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v4
        name: Checkout main repository

      - uses: actions/checkout@v4
        name: Checkout course-js-api-framework repository
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'course-js-api-framework'

      - uses: ./.github/actions/test
        with:
          environment: 'prod'